on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup node@lts
        uses: actions/setup-node@v3
        with:
          node-version: lts/*  

      - name: Installation
        run: npm ci

      - name: Type checking
        run: npm run type-check

      - name: Test
        run: npm test
