name: Update snapshots

on:
  issue_comment:
    types: [created]

jobs:
  update-snapshots:
    if: ${{ github.event.issue.pull_request && github.event.comment.body == '/update-snapshots' }}

    runs-on: ubuntu-latest

    steps:
      - uses: xt0rted/pull-request-comment-branch@v1
        id: comment-branch

      - uses: actions/checkout@v3
        if: success()
        with:
          ref: ${{ steps.comment-branch.outputs.head_ref }}

      - name: Setup node@lts
        uses: actions/setup-node@v3
        with:
          node-version: lts/*

      - name: Installation
        run: npm ci

      - name: Install Playwright
        run: npx playwright install --with-deps

      - name: Waiting for 200 from the Vercel Preview
        uses: patrickedqvist/wait-for-vercel-preview@v1.3.1
        id: waitFor200
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run e2e test
        if: success()
        run: npm run test:e2e -- --update-snapshots
        env:
          PLAYWRIGHT_TEST_BASE_URL: ${{ steps.waitFor200.outputs.url }}

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: '[CI] Update snapshots'
